name: CI - HealthTrack Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Configurar Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # ✅ Instalar Google Chrome y ChromeDriver compatibles
      - name: Instalar Google Chrome + ChromeDriver
        run: |
          sudo apt update
          sudo apt install -y wget unzip

          # Instalar Chrome 117.0.5938.92
          wget https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_117.0.5938.92-1_amd64.deb
          sudo apt install -y ./google-chrome-stable_117.0.5938.92-1_amd64.deb

          # Crear symlink por compatibilidad
          if [ ! -f /usr/bin/google-chrome ]; then
            sudo ln -s /opt/google/chrome/google-chrome /usr/bin/google-chrome
          fi

          # Instalar ChromeDriver v117.0.5938.92
          wget -O chromedriver.zip https://chromedriver.storage.googleapis.com/117.0.5938.92/chromedriver_linux64.zip
          unzip chromedriver.zip
          sudo mv chromedriver /usr/local/bin/chromedriver
          sudo chmod +x /usr/local/bin/chromedriver

      # 🔁 Compilar y ejecutar todas las pruebas (incluye Selenium)
      - name: Compilar y ejecutar pruebas
        run: mvn clean test

      # 📊 Generar reporte de cobertura
      - name: Generar reporte de cobertura
        run: mvn verify